TEST_APPCENTER_API_TOKEN="0c89ac16593e6d0c0b181f40f40ecadbe236a575"
TEST_APPCENTER_OWNER_NAME="LCoder"
APPCENTER_APP_NAME="PIFAndroid"
APPCENTER_DISTRIBUTE_APK="./app/build/outputs/apk/release/app-release.apk"

default_platform(:android)

platform :android do
  lane :build do
    gradle(task: 'clean', project_dir: './')
    gradle(task: 'assemble', build_type: 'release', project_dir: './')
  end

  lane :appcenter do
  build
  appcenter_upload(
      api_token: TEST_APPCENTER_API_TOKEN,
      owner_name: TEST_APPCENTER_OWNER_NAME,
      app_name: APPCENTER_APP_NAME,
      apk: APPCENTER_DISTRIBUTE_APK,
      destinations: 'public'
      )
  end
end